### ISSUE TITLE
Pas de doc. d'installation

### ISSUE THREAD

**Issue by jframiara** [LoutrePasSauvage/B2SLAM-AppRestoWeb#1]
On ne sait pas comment installer l'application.
Il faudrait expliquer :

 -   ce qu'il faut copier dans le PHP,
 -   comment paramétrer l'app. (user, base,...),
 -   comment installer la base de données.

**Comment by MaitreRouge** [comment]
En vrai, vous pouvez essayer de mettre votre documentation technique et/ou d'installation dans le readme.md
