### ISSUE TITLE
JSON malformé

### ISSUE THREAD

**Issue by jframiara** [LoutrePasSauvage/B2SLAM-AppRestoWeb#2]
1. Le JSON généré ne contient pas les lignes de commande.
2. De plus, il semble que l'on voit deux tableaux mélés : un avec les noms des colonnes et le second avec des indices.

Exemple :
[
  {
    "id_commande": 193,
    "0": 193,
    "id_user": 4,
    "1": 4,
    "id_etat": 1,
    "2": 1,
    "date": "2023-11-30 00:00:00",
    "3": "2023-11-30 00:00:00",
    "total_commande": "26.00",
    "4": "26.00",
    "type_conso": 0,
    "5": 0
  },
  {
    "id_commande": 194,
    "0": 194,
    "id_user": 4,
    "1": 4,
    "id_etat": 1,
    "2": 1,
    "date": "2023-11-30 00:00:00",
    "3": "2023-11-30 00:00:00",
    "total_commande": "26.00",
    "4": "26.00",
    "type_conso": 0,
    "5": 0
  },
  {
    "id_commande": 195,
    "0": 195,
    "id_user": 4,
    "1": 4,
    "id_etat": 1,
    "2": 1,
    "date": "2023-11-30 00:00:00",
    "3": "2023-11-30 00:00:00",
    "total_commande": "27.00",
    "4": "27.00",
    "type_conso": 1,
    "5": 1
  },
  {
    "id_commande": 196,
    "0": 196,
    "id_user": 4,
    "1": 4,
    "id_etat": 1,
    "2": 1,
    "date": "2024-02-29 15:51:35",
    "3": "2024-02-29 15:51:35",
    "total_commande": "29.01",
    "4": "29.01",
    "type_conso": 0,
    "5": 0
  }
]

**Comment by LoutrePasSauvage** [comment]
Corrigé 👍

**Comment by jframiara** [comment]
Ca marche pas. 
Les lignes de commande sont supprimées après la commande, ce qui fait que le JSON est vide...

**Comment by LoutrePasSauvage** [comment]
ok
